services:
  postgres:
    image: 'postgres:latest'
    container_name: 'postgres-db'
    environment:
      - 'POSTGRES_DB=postgres'
      - 'POSTGRES_PASSWORD=postgres'
      - 'POSTGRES_USER=postgres'
    ports:
      - '5433:5432'
    healthcheck:
      test: "pg_isready -d clinic_db -U clinic"
      interval: 5s
      timeout: 2s
      retries: 5
    volumes:
      - 'postgres_data:/var/lib/postgresql/data'
      - './database_init/:/docker-entrypoint-initdb.d'
  eureka:
    build: ./eureka
    ports:
      - '8761:8761'
    healthcheck:
      test: "curl --silent --fail http://localhost:8761/actuator/health | grep '\"status\":\"UP\"' || exit 1"
      interval: 5s
      timeout: 2s
      retries: 5
      start_period: 10s
    depends_on:
      postgres:
        condition: service_healthy
  config:
    build: ./config
    ports:
      - "8800:8800"
    depends_on:
      eureka:
        condition: service_healthy
    environment:
      EUREKA_URL: http://eureka:8761/eureka/
      CONFIG_URL: http://config:8800
      ACTIVE_PROFILE: dev
      SPRING_PAGE: 5
      SPRING_FLYWAY_ENABLED: 'true'
      API_PREFIX: '/api/v1'
      JWT_SECRET: 'aboba'
    healthcheck:
      test: "curl --silent --fail config:8800/actuator/health | grep UP || exit 1"
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
  gateway:
    build: ./gateway
    ports:
      - "8080:8080"
    depends_on:
      eureka:
        condition: service_healthy
      config:
        condition: service_healthy
    environment:
      EUREKA_URL: http://eureka:8761/eureka/
      CONFIG_URL: http://config:8800

  auth:
    build: ./auth
    depends_on:
      eureka:
        condition: service_healthy
      config:
        condition: service_healthy
      postgres:
        condition: service_healthy
    environment:
      EUREKA_URL: http://eureka:8761/eureka/
      CONFIG_URL: http://config:8800
      DB_HOST: postgres-db
      DB_NAME: auth_db
      DB_PORT: 5432
      DB_USER: auth
      DB_PASSWORD: auth
  analysis:
    build:
      context: ./analysis
    depends_on:
      eureka:
        condition: service_healthy
      config:
        condition: service_healthy
      postgres:
        condition: service_healthy
    environment:
      EUREKA_URL: http://eureka:8761/eureka/
      CONFIG_URL: http://config:8800
      DB_HOST: postgres-db
      DB_NAME: analysis_db
      DB_PORT: 5432
      DB_USER: analysis
      DB_PASSWORD: analysis
  doctor:
    build: ./doctor
    depends_on:
      eureka:
        condition: service_healthy
      config:
        condition: service_healthy
    environment:
      EUREKA_URL: http://eureka:8761/eureka/
      CONFIG_URL: http://config:8800
      DB_HOST: postgres-db
      DB_NAME: doctor_db
      DB_PORT: 5432
      DB_USER: doctor
      DB_PASSWORD: doctor
  document:
    build: ./document
    depends_on:
      eureka:
        condition: service_healthy
      config:
        condition: service_healthy
      postgres:
        condition: service_healthy
    environment:
      EUREKA_URL: http://eureka:8761/eureka/
      CONFIG_URL: http://config:8800
      DB_HOST: postgres-db
      DB_NAME: document_db
      DB_PORT: 5432
      DB_USER: document
      DB_PASSWORD: document
  mail:
    build: ./mail
    depends_on:
      eureka:
        condition: service_healthy
      config:
        condition: service_healthy
    environment:
      EUREKA_URL: http://eureka:8761/eureka/
      CONFIG_URL: http://config:8800
  appointment:
    build: ./appointment
    depends_on:
      eureka:
        condition: service_healthy
      config:
        condition: service_healthy
      postgres:
        condition: service_healthy
    environment:
      EUREKA_URL: http://eureka:8761/eureka/
      CONFIG_URL: http://config:8800
      DB_HOST: postgres-db
      DB_NAME: appointment_db
      DB_PORT: 5432
      DB_USER: appointment
      DB_PASSWORD: appointment
  timetable:
    build: ./timetable
    depends_on:
      eureka:
        condition: service_healthy
      config:
        condition: service_healthy
    environment:
      EUREKA_URL: http://eureka:8761/eureka/
      CONFIG_URL: http://config:8800
  patient:
    build: ./patient
    depends_on:
      eureka:
        condition: service_healthy
      config:
        condition: service_healthy
      postgres:
        condition: service_healthy
    environment:
      EUREKA_URL: http://eureka:8761/eureka/
      CONFIG_URL: http://config:8800
      DB_HOST: postgres-db
      DB_NAME: patient_db
      DB_PORT: 5432
      DB_USER: patient
      DB_PASSWORD: patient
  billing:
    build: ./billing
    depends_on:
      eureka:
        condition: service_healthy
      config:
        condition: service_healthy
    environment:
      EUREKA_URL: http://eureka:8761/eureka/
      CONFIG_URL: http://config:8800
  recipe:
    build: ./recipe
    depends_on:
      eureka:
        condition: service_healthy
      config:
        condition: service_healthy
      postgres:
        condition: service_healthy
    environment:
      EUREKA_URL: http://eureka:8761/eureka/
      CONFIG_URL: http://config:8800
      DB_HOST: postgres-db
      DB_NAME: recipe_db
      DB_PORT: 5432
      DB_USER: recipe
      DB_PASSWORD: recipe
volumes:
  postgres_data: