services:
  postgres:
    image: 'postgres:latest'
    container_name: 'postgres-db'
    environment:
      - 'POSTGRES_DB=clinic_db'
      - 'POSTGRES_PASSWORD=clinic'
      - 'POSTGRES_USER=clinic'
    ports:
      - '5432:5432'
    healthcheck:
      test: "pg_isready -d clinic_db -U clinic"
      interval: 5s
      timeout: 2s
      retries: 5
    volumes:
      - 'postgres_data:/var/lib/postgresql/data'
  eureka:
    build: ./eureka
    ports:
      - '8761:8761'
    healthcheck:
      test: "curl --silent --fail http://localhost:8761/actuator/health | grep '\"status\":\"UP\"' || exit 1"
      interval: 5s
      timeout: 2s
      retries: 5
      start_period: 10s
    depends_on:
      postgres:
        condition: service_healthy
  config:
    build: ./config
    ports:
      - "8800:8800"
    depends_on:
      eureka:
        condition: service_healthy
    environment:
      EUREKA_URL: http://eureka:8761/eureka/
      CONFIG_URL: http://config:8800
      ACTIVE_PROFILE: dev
      SPRING_PAGE: 5
      SPRING_DATASOURCE_URL: 'jdbc:postgresql://postgres-db:5432/clinic_db'
      SPRING_DATASOURCE_USERNAME: 'clinic'
      SPRING_DATASOURCE_PASSWORD: 'clinic'
      SPRING_FLYWAY_ENABLED: 'true'
      API_PREFIX: '/api/v1'
      JWT_SECRET: 'aboba'
    healthcheck:
      test: "curl --silent --fail config:8800/actuator/health | grep UP || exit 1"
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
  gateway:
    build: ./gateway
    ports:
      - "8080:8080"
    depends_on:
      eureka:
        condition: service_healthy
      config:
        condition: service_healthy
    environment:
      EUREKA_URL: http://eureka:8761/eureka/
      CONFIG_URL: http://config:8800

  auth:
    build: ./auth
    depends_on:
      eureka:
        condition: service_healthy
      config:
        condition: service_healthy
      postgres:
        condition: service_healthy
    environment:
      EUREKA_URL: http://eureka:8761/eureka/
      CONFIG_URL: http://config:8800
  analysis:
    build:
      context: ./analysis
    depends_on:
      eureka:
        condition: service_healthy
      config:
        condition: service_healthy
      postgres:
        condition: service_healthy
    environment:
      EUREKA_URL: http://eureka:8761/eureka/
      CONFIG_URL: http://config:8800
  doctor:
    build: ./doctor
    depends_on:
      eureka:
        condition: service_healthy
      config:
        condition: service_healthy
    environment:
      EUREKA_URL: http://eureka:8761/eureka/
      CONFIG_URL: http://config:8800
  document:
    build: ./document
    depends_on:
      eureka:
        condition: service_healthy
      config:
        condition: service_healthy
      postgres:
        condition: service_healthy
    environment:
      EUREKA_URL: http://eureka:8761/eureka/
      CONFIG_URL: http://config:8800
  mail:
    build: ./mail
    depends_on:
      eureka:
        condition: service_healthy
      config:
        condition: service_healthy
    environment:
      EUREKA_URL: http://eureka:8761/eureka/
      CONFIG_URL: http://config:8800
  appointment:
    build: ./appointment
    depends_on:
      eureka:
        condition: service_healthy
      config:
        condition: service_healthy
      postgres:
        condition: service_healthy
    environment:
      EUREKA_URL: http://eureka:8761/eureka/
      CONFIG_URL: http://config:8800
  timetable:
    build: ./timetable
    depends_on:
      eureka:
        condition: service_healthy
      config:
        condition: service_healthy
    environment:
      EUREKA_URL: http://eureka:8761/eureka/
      CONFIG_URL: http://config:8800
  patient:
    build: ./patient
    depends_on:
      eureka:
        condition: service_healthy
      config:
        condition: service_healthy
      postgres:
        condition: service_healthy
    environment:
      EUREKA_URL: http://eureka:8761/eureka/
      CONFIG_URL: http://config:8800
  billing:
    build: ./billing
    depends_on:
      eureka:
        condition: service_healthy
      config:
        condition: service_healthy
    environment:
      EUREKA_URL: http://eureka:8761/eureka/
      CONFIG_URL: http://config:8800
  recipe:
    build: ./recipe
    depends_on:
      eureka:
        condition: service_healthy
      config:
        condition: service_healthy
      postgres:
        condition: service_healthy
    environment:
      EUREKA_URL: http://eureka:8761/eureka/
      CONFIG_URL: http://config:8800
volumes:
  postgres_data: