spring:
  application:
    name: appointment
    page-size: 5
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5433}/${DB_NAME:postgres}
    username: ${DB_USER:postgres}
    password: ${DB_PASSWORD:1234}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate.ddl-auto: none
    show-sql: true
  flyway:
    baselineOnMigrate: true
    locations: classpath:db/migration,classpath:/db/testmigration
    schemas: public
    enabled: true
  devtools.restart.enabled: true
  jackson.property-naming-strategy: SNAKE_CASE

springdoc.api-docs.path: /api-docs

springdoc.swagger-ui.path: /api

server:
  port: 8888
  servlet.context-path: /

doctor.service.url: ${DOCTOR_SERVICE:http://doctor:8888/api/doctors}
patient.service.url: ${PATIENT_SERVICE:http://patient:8888/api/patients}
mail.service.url: ${MAIL_SERVICE:http://mail:8888/api/mail}