spring:
  application:
    name: auth-service
    page: ${SPRING_PAGE:5}
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5433}/${DB_NAME:postgres}
    password: ${DB_PASSWORD:1234}
    username: ${DB_USER:postgres}
  jackson:
    property-naming-strategy: SNAKE_CASE

server:
  port: 8084

# API prefix
api:
  prefix: /api/v1

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URL:http://eureka:8761/eureka/}
keys:
  privateKey: |
    MIIEvgIBADANBgkqhkiG9w0BAQEFAASCBKgwggSkAgEAAoIBAQCtA5K9sIy6a7nB
    uTuce902FdHjSu+4XlihV3BWBNKekTF907rplQOJ/DgMqjMSE8qUV3OxJc5a/Hzr
    BMGsWIMSQHEbRdEiXDARWgxaYnWBmbJ30cjjJnempzm1HL3y1JoYOnAdxLehiVbI
    BD5AqjfqKgvdONAdv/hTm5LnlJFQOQRNNa2QfWBFPcv+4uIyyascifZl/vd4Hx+N
    fsJzBAo+V6XZbyAr29mOubRBj+q7OqOdeSjJ9aH3CSWxKeC+VSSKhaMoGN3FeohU
    ZvAXmiRSRDqUEH8TNkF+OXzSBz0klL/lys6X5ToT6nDzy2SHZ7v08WmmYi79lnku
    CMRw8h5NAgMBAAECggEABDNoQnVRMWyQrdC4zw+d2yST/EwTPnuB9Obp2hjTYVi+
    piK4MNg2pgjK9pnCVC/JVSk7bKNxm3lycgVjS3M5uX15kZM0JPyuiRlR3/bwifVI
    pUqhcUx7jr8UMl7QiN8bH7f5hWuDluc+BWy+8zR+149uStCIkxRYa/VEz50mmxdB
    GBLQoqKz5JCpLYW+Yu9yvphtwXtM1qtAEbK6f42Diu+H78TgAfMrQ4Vr+Q5a7CE7
    dGFe7ZTcpeegu9J8mrIe8L9lLalVMB+UCMYsh4+aguP6+L5BzQ2z5tIwsLNxxOpQ
    9XIpEDIhEYApvYNwmjP0Kikxi5eZ9TWmVTG0J0vVyQKBgQDV7vNMmzfU/F90kz4i
    Jo3lGczKh+XBGuEAc94QwrzpUgczvqORVC+b81Iz5H1KKKtplK3t99G8aAczNQsK
    Fm3TwJv8gX+O8MiNxI3tlnO6Yy5PfcST6WUJ2fDr1dXPEFO+Ogjh0m2UAxfpD2An
    5A7YMwtDv1LAr3Couy1wGkjdxQKBgQDPCM54siFhvAzBpvC9hn0PzqqdGeWEt7kn
    /zxam3twfH2samFpybAl2MAGyD8S4UkHf/5hUavX698N4fZPATxwdoXgjvKe1dvn
    HoO8Hzu4AHZEa3xgZQ+GeBEkNSnAtqX6lxsCtuB1qQSGk6sgs9QQgPdzHn//nDKE
    VmAKIfmO6QKBgQChzjj2l++Ch98qrLMx4TcxMHJUPLTpeQr07K3ov2Fil0gbOvU7
    1hCsQzzJQugATwJWuL1UXzui5IuNj3DqEEzA+8z/DnMMCdGmaCNwr3qYXquIM/ea
    Z8yjxtMRjIpKMm8kUYCmTCHU8QIEpDx172fK3dCHTQ2p7wemluum/jpegQKBgQCK
    92hPz5FknusZGUtCjAFqGNigtv8+hGu+Ey6Zyv+iU42vq4BTl9Oqs8DBTKw5qgpx
    BFLlVAK63lJMaT4Bbdz5yDS4tHrabsY6blsSbQySx4ybBGLp+SvgoLswyJaMCo2C
    lObGfaZQk/C7vGcDfnF72nU+Sly0YE3wUmIIqyFt8QKBgCBdlzseJqJTW/AKoot7
    x5S0HT5l5a5yzwalPwf5gZ5U6YFdO7I4es2VPs8/YQm6RdznnIZFGzJrf4fsnmBk
    nk2HVwYe+osn7uRhxCsMbrpKC1j6p2oWVhzCtnxz5Yxmzsi/8gUeiavQPGtZ6Y7p
    shH36+NMhlTvIIuzv+0IWIOS
  publicKey: |
    MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEArQOSvbCMumu5wbk7nHvd
    NhXR40rvuF5YoVdwVgTSnpExfdO66ZUDifw4DKozEhPKlFdzsSXOWvx86wTBrFiD
    EkBxG0XRIlwwEVoMWmJ1gZmyd9HI4yZ3pqc5tRy98tSaGDpwHcS3oYlWyAQ+QKo3
    6ioL3TjQHb/4U5uS55SRUDkETTWtkH1gRT3L/uLiMsmrHIn2Zf73eB8fjX7CcwQK
    Plel2W8gK9vZjrm0QY/quzqjnXkoyfWh9wklsSngvlUkioWjKBjdxXqIVGbwF5ok
    UkQ6lBB/EzZBfjl80gc9JJS/5crOl+U6E+pw88tkh2e79PFppmIu/ZZ5LgjEcPIe
    TQIDAQAB