server:
  port: '8888'
  servlet:
    context-path: /
spring:
  application:
    name: document
    page-size: '5'
  datasource:
    driver-class-name: org.postgresql.Driver
    password: ${DB_PASSWORD:1234}
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5433}/${DB_NAME:postgres}
    username: ${DB_USER:postgres}
  devtools:
    restart:
      enabled: 'true'
  flyway:
    baselineOnMigrate: 'true'
    enabled: 'true'
    locations: classpath:db/migration,classpath:/db/testmigration
    schemas: public
  jackson:
    property-naming-strategy: SNAKE_CASE
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: 'true'
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /api
