spring:
  application:
    name: gateway
  cloud:
    gateway:
      routes:
        - id: tag-service
          uri: lb://tag-service
          predicates:
            - Path=/api/v1/tags/**
          filters:
            - name: CircuitBreaker
              args:
                name: tagCircuitBreaker
                fallbackUri: forward:/fallback
        - id: auth-service
          uri: lb://auth-service
          predicates:
            - Path=/api/v1/auth/**
          filters:
            - name: CircuitBreaker
              args:
                name: authCircuitBreaker
                fallbackUri: forward:/fallback
        - id: studio-service
          uri: lb://studio-service
          predicates:
            - Path=/api/v1/studio/**
          filters:
            - name: CircuitBreaker
              args:
                name: studioCircuitBreaker
                fallbackUri: forward:/fallback
        - id: rating-service
          uri: lb://rating-service
          predicates:
            - Path=/api/v1/content/rating/**
          filters:
            - name: CircuitBreaker
              args:
                name: ratingCircuitBreaker
                fallbackUri: forward:/fallback
        - id: review-service
          uri: lb://review-service
          predicates:
            - Path=/api/v1/content/review/**
          filters:
            - name: CircuitBreaker
              args:
                name: reviewCircuitBreaker
                fallbackUri: forward:/fallback
        - id: content-service
          uri: lb://content-service
          predicates:
            - Path=/api/v1/content/**
          filters:
            - name: CircuitBreaker
              args:
                name: contentCircuitBreaker
                fallbackUri: forward:/fallback
server:
  port: 8080

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URL:http://eureka:8761/eureka/}

resilience4j:
  circuitbreaker:
    configs:
      clinic:
        slidingWindowSize: 10
        slidingWindowType: COUNT_BASED
        failureRateThreshold: 52
        slowCallRateThreshold: 75
        waitDurationInOpenState: 15s
        permittedNumberOfCallsInHalfOpenState: 2
        minimumNumberOfCalls: 10
        slowCallDurationThreshold: 15s
    instances:
      tagCircuitBreaker:
        base-config: clinic
      authCircuitBreaker:
        base-config: clinic
      studioCircuitBreaker:
        base-config: clinic
      ratingCircuitBreaker:
        base-config: clinic
      reviewCircuitBreaker:
        base-config: clinic
      contentCircuitBreaker:
        base-config: clinic