spring:
  application:
    name: gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: auth
          uri: lb://auth
          predicates:
            - Path=/api/v1/auth/**
          filters:
            - name: CircuitBreaker
              args:
                name: authCB
                fallbackUri: forward:/fallback
        - id: analysis
          uri: lb://analysis
          predicates:
            - Path=/api/analyses/**
          filters:
            - name: CircuitBreaker
              args:
                name: analysisCB
                fallbackUri: forward:/fallback
        - id: appointment
          uri: lb://appointment
          predicates:
            - Path=/api/appointments/**, /api/appointments-type/**
          filters:
            - name: CircuitBreaker
              args:
                name: appointmentCB
                fallbackUri: forward:/fallback
        - id: billing
          uri: lb://billing
          predicates:
            - Path=/api/billing/**
          filters:
            - name: CircuitBreaker
              args:
                name: billingCB
                fallbackUri: forward:/fallback
        - id: doctor
          uri: lb://doctor
          predicates:
            - Path=/api/doctors/**
          filters:
            - name: CircuitBreaker
              args:
                name: doctorCB
                fallbackUri: forward:/fallback
        - id: document
          uri: lb://document
          predicates:
            - Path=/api/documents/**
          filters:
            - name: CircuitBreaker
              args:
                name: documentCB
                fallbackUri: forward:/fallback
        - id: mail
          uri: lb://mail
          predicates:
            - Path=/api/mail/**
          filters:
            - name: CircuitBreaker
              args:
                name: mailCB
                fallbackUri: forward:/fallback
        - id: patient
          uri: lb://patient
          predicates:
            - Path=/api/patients/**
          filters:
            - name: CircuitBreaker
              args:
                name: patientCB
                fallbackUri: forward:/fallback
        - id: recipe
          uri: lb://recipe
          predicates:
            - Path=/api/recipes/**
          filters:
            - name: CircuitBreaker
              args:
                name: recipeCB
                fallbackUri: forward:/fallback
        - id: timetable
          uri: lb://timetable
          predicates:
            - Path=/api/timetable/**
          filters:
            - name: CircuitBreaker
              args:
                name: timetableCB
                fallbackUri: forward:/fallback
server:
  port: 8080

eureka:
  client:
    instance:
      preferIpAddress: true
    fetchRegistry: true
    registerWithEureka: false
    serviceUrl:
      defaultZone: ${EUREKA_URL:http://eureka:8761/eureka/}

resilience4j:
  circuitbreaker:
    configs:
      clinic:
        slidingWindowSize: 10
        slidingWindowType: COUNT_BASED
        failureRateThreshold: 52
        slowCallRateThreshold: 75
        waitDurationInOpenState: 15s
        permittedNumberOfCallsInHalfOpenState: 2
        minimumNumberOfCalls: 10
        slowCallDurationThreshold: 15s
    instances:
      authCB:
        base-config: clinic
      analysisCB:
        base-config: clinic
      appointmentCB:
        base-config: clinic
      billingCB:
        base-config: clinic
      doctorCB:
        base-config: clinic
      documentCB:
        base-config: clinic
      mailCB:
        base-config: clinic
      patientCB:
        base-config: clinic
      recipeCB:
        base-config: clinic
      timetableCB:
        base-config: clinic