spring:
  cloud:
    import-check:
      enabled: false
    config:
      enable: false
  application:
    name: billing
    page-size: 5
  devtools.restart.enabled: true
  jackson.property-naming-strategy: SNAKE_CASE

springdoc.api-docs.path: /api-docs

springdoc.swagger-ui.path: /api

server:
  port: 8889
  servlet.context-path: /


appointment.service.url: http://localhost:8888/api/appointments/
patient.service.url: http://localhost:8080/api/patients/